window.VERTICE_CONFIG = {
  brand: 'Vértice Imóveis',
  whatsapp: '5511999999999',
  email: 'contato@verticeimoveis.com.br',
  instagram: '@verticeimoveis',
  address: 'Av. Portugal, 580 • Santo André/SP',
  creci: 'CRECI 000000-F • Demonstrativo'
};

const IMG = {
  house1: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
  house2: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',
  house3: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85',
  house4: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',
  int1: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85',
  int2: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85',
  int3: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
  int4: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
  apt1: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=85',
  apt2: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=85',
  apt3: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=85',
  apt4: 'https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=1600&q=85',
  land1: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85',
  commercial1: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85',
  commercial2: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=85'
};

window.VERTICE_PROPERTIES = [
  {
    id: 1,
    slug: 'casa-moderna-jardim',
    reference: 'VT1024',
    title: 'Casa Moderna em Condomínio',
    purpose: 'comprar',
    type: 'Casa',
    city: 'Santo André',
    neighborhood: 'Jardim',
    price: 890000,
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking: 2,
    area: 180,
    featured: true,
    newProperty: true,
    description: 'Uma casa contemporânea pensada para quem valoriza integração, conforto e excelente iluminação natural. A área social conecta sala, jantar e cozinha, enquanto o espaço gourmet amplia as possibilidades de convivência.',
    features: ['Condomínio fechado', 'Área gourmet', 'Suíte master', 'Cozinha planejada', 'Lavabo', 'Quintal', 'Ar-condicionado', 'Segurança 24h'],
    images: [IMG.house1, IMG.int1, IMG.int2, IMG.int3]
  },
  {
    id: 2,
    slug: 'apartamento-varanda-gourmet-sbc',
    reference: 'VT1187',
    title: 'Apartamento com Varanda Gourmet',
    purpose: 'comprar',
    type: 'Apartamento',
    city: 'São Bernardo do Campo',
    neighborhood: 'Nova Petrópolis',
    price: 650000,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parking: 2,
    area: 92,
    featured: true,
    newProperty: false,
    description: 'Apartamento moderno com planta bem distribuída, varanda gourmet integrada à sala e condomínio completo. Uma opção equilibrada para famílias que buscam praticidade e boa localização.',
    features: ['Varanda gourmet', 'Suíte', 'Planejados', 'Piscina', 'Academia', 'Salão de festas', 'Portaria 24h'],
    images: [IMG.apt1, IMG.apt2, IMG.int4, IMG.apt3]
  },
  {
    id: 3,
    slug: 'sobrado-contemporaneo-maua',
    reference: 'VT1103',
    title: 'Sobrado Contemporâneo',
    purpose: 'comprar',
    type: 'Sobrado',
    city: 'Mauá',
    neighborhood: 'Vila Bocaina',
    price: 720000,
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking: 3,
    area: 160,
    featured: true,
    newProperty: true,
    description: 'Sobrado com arquitetura atual, ambientes amplos e acabamentos de bom padrão. A área externa conta com espaço para receber amigos e família com conforto.',
    features: ['Área gourmet', 'Lavabo', 'Suíte', '3 vagas', 'Sala integrada', 'Iluminação em LED'],
    images: [IMG.house2, IMG.house3, IMG.int1, IMG.int4]
  },
  {
    id: 4,
    slug: 'apartamento-alto-padrao-scs',
    reference: 'VT1218',
    title: 'Apartamento Alto Padrão',
    purpose: 'comprar',
    type: 'Apartamento',
    city: 'São Caetano do Sul',
    neighborhood: 'Santa Paula',
    price: 1280000,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parking: 3,
    area: 155,
    featured: true,
    newProperty: false,
    description: 'Apartamento de alto padrão com três suítes, varanda generosa e acabamento sofisticado. Condomínio com lazer completo em uma das regiões mais valorizadas da cidade.',
    features: ['3 suítes', 'Varanda gourmet', 'Elevador privativo', '3 vagas', 'Piscina', 'Academia', 'Concierge'],
    images: [IMG.apt3, IMG.int3, IMG.int2, IMG.apt4]
  },
  {
    id: 5,
    slug: 'casa-area-gourmet-ribeirao-pires',
    reference: 'VT1076',
    title: 'Casa com Área Gourmet e Jardim',
    purpose: 'comprar',
    type: 'Casa',
    city: 'Ribeirão Pires',
    neighborhood: 'Pastoril',
    price: 780000,
    bedrooms: 4,
    suites: 2,
    bathrooms: 3,
    parking: 4,
    area: 240,
    featured: true,
    newProperty: false,
    description: 'Casa espaçosa cercada por verde, com área gourmet, jardim e ambientes generosos. Ideal para quem busca tranquilidade sem abrir mão de uma boa estrutura.',
    features: ['Jardim', 'Churrasqueira', '2 suítes', '4 vagas', 'Escritório', 'Quintal amplo'],
    images: [IMG.house4, IMG.house1, IMG.int1, IMG.land1]
  },
  {
    id: 6,
    slug: 'apartamento-aluguel-jardim',
    reference: 'VT2041',
    title: 'Apartamento para Alugar no Jardim',
    purpose: 'alugar',
    type: 'Apartamento',
    city: 'Santo André',
    neighborhood: 'Jardim',
    price: 3200,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking: 1,
    area: 78,
    featured: true,
    newProperty: true,
    description: 'Apartamento pronto para morar, com sala integrada à varanda, armários planejados e localização estratégica próxima a serviços e gastronomia.',
    features: ['Mobiliado parcialmente', 'Suíte', '1 vaga', 'Portaria', 'Varanda', 'Planejados'],
    images: [IMG.apt2, IMG.int4, IMG.apt1, IMG.int3]
  },
  {
    id: 7,
    slug: 'casa-terrea-assuncao',
    reference: 'VT1140',
    title: 'Casa Térrea com Quintal',
    purpose: 'comprar',
    type: 'Casa',
    city: 'São Bernardo do Campo',
    neighborhood: 'Assunção',
    price: 595000,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parking: 2,
    area: 145,
    featured: false,
    newProperty: false,
    description: 'Casa térrea funcional, com quintal ensolarado e planta confortável. Boa opção para famílias que preferem praticidade e fácil circulação.',
    features: ['Casa térrea', 'Quintal', 'Suíte', '2 vagas', 'Edícula', 'Cozinha ampla'],
    images: [IMG.house3, IMG.int1, IMG.int2, IMG.house2]
  },
  {
    id: 8,
    slug: 'studio-mobiliado-sao-caetano',
    reference: 'VT2077',
    title: 'Studio Mobiliado',
    purpose: 'alugar',
    type: 'Apartamento',
    city: 'São Caetano do Sul',
    neighborhood: 'Barcelona',
    price: 2650,
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parking: 1,
    area: 44,
    featured: false,
    newProperty: true,
    description: 'Studio mobiliado, compacto e muito bem resolvido, ideal para quem busca mobilidade e conveniência em uma região com infraestrutura completa.',
    features: ['Mobiliado', '1 vaga', 'Academia', 'Lavanderia coletiva', 'Coworking', 'Portaria 24h'],
    images: [IMG.apt4, IMG.apt2, IMG.int4, IMG.int2]
  },
  {
    id: 9,
    slug: 'terreno-condominio-ribeirao-pires',
    reference: 'VT1301',
    title: 'Terreno em Condomínio Fechado',
    purpose: 'comprar',
    type: 'Terreno',
    city: 'Ribeirão Pires',
    neighborhood: 'Ouro Fino',
    price: 310000,
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parking: 0,
    area: 420,
    featured: false,
    newProperty: false,
    description: 'Terreno com ótima topografia em condomínio residencial cercado por natureza. Excelente oportunidade para construir um projeto personalizado.',
    features: ['Condomínio fechado', '420 m²', 'Boa topografia', 'Segurança', 'Área verde'],
    images: [IMG.land1, IMG.house4, IMG.house1, IMG.house2]
  },
  {
    id: 10,
    slug: 'sala-comercial-centro-santo-andre',
    reference: 'VT3012',
    title: 'Sala Comercial Pronta para Uso',
    purpose: 'alugar',
    type: 'Comercial',
    city: 'Santo André',
    neighborhood: 'Centro',
    price: 4100,
    bedrooms: 0,
    suites: 0,
    bathrooms: 2,
    parking: 2,
    area: 96,
    featured: false,
    newProperty: true,
    description: 'Conjunto comercial com excelente apresentação, recepção, salas de atendimento e estrutura pronta para empresas e profissionais liberais.',
    features: ['Recepção', 'Ar-condicionado', '2 vagas', 'Elevadores', 'Portaria', 'Copa'],
    images: [IMG.commercial1, IMG.commercial2, IMG.int4, IMG.int3]
  },
  {
    id: 11,
    slug: 'apartamento-pq-nacoes',
    reference: 'VT1196',
    title: 'Apartamento com Vista Livre',
    purpose: 'comprar',
    type: 'Apartamento',
    city: 'Santo André',
    neighborhood: 'Parque das Nações',
    price: 485000,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking: 1,
    area: 69,
    featured: false,
    newProperty: false,
    description: 'Apartamento em andar alto, com vista livre, boa incidência de luz natural e condomínio com lazer para toda a família.',
    features: ['Andar alto', 'Vista livre', 'Suíte', 'Piscina', 'Playground', '1 vaga'],
    images: [IMG.apt1, IMG.apt3, IMG.int2, IMG.int1]
  },
  {
    id: 12,
    slug: 'sobrado-aluguel-maua',
    reference: 'VT2092',
    title: 'Sobrado Amplo para Locação',
    purpose: 'alugar',
    type: 'Sobrado',
    city: 'Mauá',
    neighborhood: 'Jardim Haydee',
    price: 3800,
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking: 2,
    area: 170,
    featured: false,
    newProperty: false,
    description: 'Sobrado espaçoso com dormitórios confortáveis, quintal e garagem para dois veículos. Uma opção completa para famílias.',
    features: ['Suíte', 'Quintal', '2 vagas', 'Lavabo', 'Sala ampla', 'Área de serviço'],
    images: [IMG.house2, IMG.house3, IMG.int1, IMG.int3]
  }
];
