const STORAGE_KEY='aurea_appointments';
const services=[
{id:'limpeza-de-pele',name:'Limpeza de Pele',duration:60,price:120,display:'R$ 120'},
{id:'peeling-facial',name:'Peeling Facial',duration:45,price:150,display:'R$ 150'},
{id:'microagulhamento',name:'Microagulhamento',duration:60,price:250,display:'R$ 250'},
{id:'drenagem-linfatica',name:'Drenagem Linfática',duration:60,price:130,display:'R$ 130'},
{id:'massagem-modeladora',name:'Massagem Modeladora',duration:60,price:140,display:'R$ 140'},
{id:'depilacao-laser',name:'Depilação a Laser',duration:45,price:null,display:'Sob avaliação'},
{id:'protocolo-facial',name:'Protocolo Facial',duration:60,price:180,display:'R$ 180'},
{id:'protocolo-corporal',name:'Protocolo Corporal',duration:90,price:null,display:'Sob avaliação'}];
const professionals=[
{id:'sem-preferencia',name:'Sem preferência',specialty:'Melhor disponibilidade',image:null},
{id:'marina-costa',name:'Marina Costa',specialty:'Biomédica Esteta',image:'images/profissional-marina.webp'},
{id:'camila-fernandes',name:'Camila Fernandes',specialty:'Esteticista corporal',image:'images/profissional-camila.webp'},
{id:'laura-martins',name:'Laura Martins',specialty:'Esteticista facial',image:'images/profissional-laura.webp'}];
const times=['09:00','09:30','10:00','10:30','11:00','11:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00'];
let state={step:1,service:null,professional:null,date:null,time:null,dateOffset:0};

function dateISO(date){return date.toISOString().slice(0,10)}
function addDays(base,days){const d=new Date(base);d.setDate(d.getDate()+days);return d}
function seedDemo(){if(localStorage.getItem(STORAGE_KEY))return;const today=new Date();const demo=[
{code:'AUR-31024',client:'Fernanda Oliveira',phone:'(11) 98888-1201',email:'fernanda@email.com',service:'Limpeza de Pele',serviceId:'limpeza-de-pele',professional:'Marina Costa',professionalId:'marina-costa',date:dateISO(addDays(today,1)),time:'09:00',duration:60,price:120,status:'Confirmado',notes:''},
{code:'AUR-42518',client:'Amanda Souza',phone:'(11) 97777-5310',email:'amanda@email.com',service:'Microagulhamento',serviceId:'microagulhamento',professional:'Marina Costa',professionalId:'marina-costa',date:dateISO(addDays(today,1)),time:'10:30',duration:60,price:250,status:'Confirmado',notes:''},
{code:'AUR-77304',client:'Carolina Mendes',phone:'(11) 96666-9402',email:'carolina@email.com',service:'Drenagem Linfática',serviceId:'drenagem-linfatica',professional:'Camila Fernandes',professionalId:'camila-fernandes',date:dateISO(addDays(today,1)),time:'13:30',duration:60,price:130,status:'Pendente',notes:''},
{code:'AUR-81290',client:'Juliana Costa',phone:'(11) 95555-2030',email:'juliana@email.com',service:'Protocolo Facial',serviceId:'protocolo-facial',professional:'Laura Martins',professionalId:'laura-martins',date:dateISO(addDays(today,2)),time:'16:00',duration:60,price:180,status:'Confirmado',notes:''}];localStorage.setItem(STORAGE_KEY,JSON.stringify(demo));}
seedDemo();

const serviceGrid=document.getElementById('serviceGrid'),professionalGrid=document.getElementById('professionalGrid'),dateGrid=document.getElementById('dateGrid'),morning=document.getElementById('morningTimes'),afternoon=document.getElementById('afternoonTimes');
const nextBtn=document.getElementById('nextBtn'),backBtn=document.getElementById('backBtn');
function money(v){return v==null?'Sob avaliação':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)}
function renderServices(){serviceGrid.innerHTML=services.map(s=>`<button class="option-card ${state.service?.id===s.id?'selected':''}" data-id="${s.id}"><strong>${s.name}</strong><p>${s.duration} minutos</p><span>${s.display}</span></button>`).join('');serviceGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.service=services.find(s=>s.id===b.dataset.id);renderServices();updateSummary();validateStep()})}
function renderProfessionals(){professionalGrid.innerHTML=professionals.map(p=>`<button class="professional-card ${state.professional?.id===p.id?'selected':''}" data-id="${p.id}">${p.image?`<img src="${p.image}" alt="${p.name}">`:`<span class="avatar-fallback">A</span>`}<span><strong>${p.name}</strong><span>${p.specialty}</span></span></button>`).join('');professionalGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.professional=professionals.find(p=>p.id===b.dataset.id);renderProfessionals();updateSummary();validateStep()})}
function renderDates(){const today=new Date();today.setHours(12,0,0,0);const start=addDays(today,state.dateOffset);const fmtMonth=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'});document.getElementById('dateRangeLabel').textContent=fmtMonth.format(start);dateGrid.innerHTML='';for(let i=0;i<6;i++){const d=addDays(start,i),disabled=d.getDay()===0||d<today,iso=dateISO(d),btn=document.createElement('button');btn.className=`date-card ${disabled?'disabled':''} ${state.date===iso?'selected':''}`;btn.disabled=disabled;btn.innerHTML=`<span>${new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(d).replace('.','').toUpperCase()}</span><strong>${d.getDate()}</strong><small>${new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(d).replace('.','')}</small>`;btn.onclick=()=>{state.date=iso;state.time=null;renderDates();renderTimes();updateSummary();validateStep()};dateGrid.appendChild(btn)}}
function occupiedTimes(){const appointments=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');const prof=state.professional?.id==='sem-preferencia'?null:state.professional?.id;return appointments.filter(a=>a.date===state.date&&a.status!=='Cancelado'&&(!prof||a.professionalId===prof)).map(a=>a.time)}
function renderTimes(){const occupied=new Set(occupiedTimes());const simulated=new Set(['10:30','14:00','16:30']);const create=t=>`<button class="time-btn ${state.time===t?'selected':''}" data-time="${t}" ${(occupied.has(t)||simulated.has(t))?'disabled':''}>${t}</button>`;morning.innerHTML=times.filter(t=>t<'12:00').map(create).join('');afternoon.innerHTML=times.filter(t=>t>'12:00').map(create).join('');document.querySelectorAll('.time-btn:not(:disabled)').forEach(b=>b.onclick=()=>{state.time=b.dataset.time;renderTimes();updateSummary();validateStep()})}
function updateSummary(){document.getElementById('summaryService').textContent=state.service?.name||'—';document.getElementById('summaryProfessional').textContent=state.professional?.name||'—';document.getElementById('summaryDate').textContent=state.date?new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date(state.date+'T12:00:00')):'—';document.getElementById('summaryTime').textContent=state.time||'—';document.getElementById('summaryDuration').textContent=state.service?`${state.service.duration} min`:'—';document.getElementById('summaryPrice').textContent=state.service?money(state.service.price):'—'}
function validateStep(){let ok=false;if(state.step===1)ok=!!state.service;if(state.step===2)ok=!!state.professional;if(state.step===3)ok=!!state.date;if(state.step===4)ok=!!state.time;if(state.step===5)ok=true;nextBtn.disabled=!ok;nextBtn.textContent=state.step===5?'Confirmar agendamento':'Continuar';backBtn.disabled=state.step===1}
function showStep(){document.querySelectorAll('.step-panel').forEach(p=>p.classList.toggle('active',Number(p.dataset.step)===state.step));document.querySelectorAll('#progressSteps span').forEach((s,i)=>s.classList.toggle('active',i<state.step));document.getElementById('progressFill').style.width=`${state.step*20}%`;validateStep();window.scrollTo({top:0,behavior:'smooth'})}
function resolveProfessional(){if(state.professional.id!=='sem-preferencia')return state.professional;const opts=professionals.slice(1);return opts[Math.floor(Math.random()*opts.length)]}
function generateCode(){return 'AUR-'+Math.floor(10000+Math.random()*89999)}
function submitBooking(){const name=document.getElementById('clientName').value.trim(),phone=document.getElementById('clientPhone').value.trim(),email=document.getElementById('clientEmail').value.trim(),notes=document.getElementById('clientNotes').value.trim(),privacy=document.getElementById('privacyCheck').checked;if(name.length<3||phone.replace(/\D/g,'').length<10||!privacy){alert('Preencha nome, WhatsApp e aceite a política de privacidade.');return}const occupied=new Set(occupiedTimes());if(occupied.has(state.time)){alert('Este horário não está mais disponível. Escolha outra opção.');state.step=4;renderTimes();showStep();return}const prof=resolveProfessional(),code=generateCode();const appt={code,client:name,phone,email,service:state.service.name,serviceId:state.service.id,professional:prof.name,professionalId:prof.id,date:state.date,time:state.time,duration:state.service.duration,price:state.service.price,status:'Confirmado',notes,createdAt:new Date().toISOString()};const arr=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');arr.push(appt);localStorage.setItem(STORAGE_KEY,JSON.stringify(arr));document.getElementById('successName').textContent=name.split(' ')[0];document.getElementById('successCode').textContent=code;document.getElementById('successDetails').innerHTML=`<strong>${appt.service}</strong><span>${new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date(appt.date+'T12:00:00'))}</span><span>${appt.time} • ${appt.professional}</span><span>${money(appt.price)}</span>`;const msg=encodeURIComponent(`Olá! Realizei um agendamento pelo site demonstrativo da Auréa.\n\nCódigo: ${code}\nProcedimento: ${appt.service}\nProfissional: ${appt.professional}\nData: ${new Intl.DateTimeFormat('pt-BR').format(new Date(appt.date+'T12:00:00'))}\nHorário: ${appt.time}`);document.getElementById('successWhatsapp').href=`https://wa.me/5511999990000?text=${msg}`;const screen=document.getElementById('successScreen');screen.classList.add('show');screen.setAttribute('aria-hidden','false')}
nextBtn.onclick=()=>{if(state.step<5){state.step++;showStep();if(state.step===4)renderTimes()}else submitBooking()};backBtn.onclick=()=>{if(state.step>1){state.step--;showStep()}};document.getElementById('nextDates').onclick=()=>{state.dateOffset+=6;renderDates()};document.getElementById('prevDates').onclick=()=>{state.dateOffset=Math.max(0,state.dateOffset-6);renderDates()};document.getElementById('clientPhone').addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,11);if(v.length>6)v=v.replace(/(\d{2})(\d{5})(\d+)/,'($1) $2-$3');else if(v.length>2)v=v.replace(/(\d{2})(\d+)/,'($1) $2');e.target.value=v});
const params=new URLSearchParams(location.search);const serviceParam=params.get('servico'),professionalParam=params.get('profissional');if(serviceParam){state.service=services.find(s=>s.id===serviceParam)||null}if(professionalParam){state.professional=professionals.find(p=>p.id===professionalParam)||null}
renderServices();renderProfessionals();renderDates();renderTimes();updateSummary();showStep();
