// Autenticação exclusivamente demonstrativa. Não use este padrão em produção.
const STORAGE_KEY='aurea_appointments',SESSION_KEY='aurea_admin_demo';
const treatments=[['Limpeza de Pele','Facial','60 min','R$ 120'],['Peeling Facial','Facial','45 min','R$ 150'],['Microagulhamento','Tecnologia','60 min','R$ 250'],['Drenagem Linfática','Corporal','60 min','R$ 130'],['Massagem Modeladora','Corporal','60 min','R$ 140'],['Depilação a Laser','Tecnologia','30–60 min','Sob avaliação'],['Protocolo Facial','Facial','60 min','R$ 180'],['Protocolo Corporal','Corporal','60–90 min','Sob avaliação']];
function dateISO(date){return date.toISOString().slice(0,10)}function addDays(base,days){const d=new Date(base);d.setDate(d.getDate()+days);return d}function todayISO(){return dateISO(new Date())}
function demoData(){const t=new Date();return[
{code:'AUR-31024',client:'Fernanda Oliveira',phone:'(11) 98888-1201',email:'fernanda@email.com',service:'Limpeza de Pele',serviceId:'limpeza-de-pele',professional:'Marina Costa',professionalId:'marina-costa',date:todayISO(),time:'09:00',duration:60,price:120,status:'Confirmado',notes:''},
{code:'AUR-42518',client:'Amanda Souza',phone:'(11) 97777-5310',email:'amanda@email.com',service:'Microagulhamento',serviceId:'microagulhamento',professional:'Marina Costa',professionalId:'marina-costa',date:todayISO(),time:'10:30',duration:60,price:250,status:'Confirmado',notes:''},
{code:'AUR-77304',client:'Carolina Mendes',phone:'(11) 96666-9402',email:'carolina@email.com',service:'Drenagem Linfática',serviceId:'drenagem-linfatica',professional:'Camila Fernandes',professionalId:'camila-fernandes',date:todayISO(),time:'13:30',duration:60,price:130,status:'Pendente',notes:''},
{code:'AUR-81290',client:'Juliana Costa',phone:'(11) 95555-2030',email:'juliana@email.com',service:'Protocolo Facial',serviceId:'protocolo-facial',professional:'Laura Martins',professionalId:'laura-martins',date:todayISO(),time:'16:00',duration:60,price:180,status:'Confirmado',notes:''},
{code:'AUR-23910',client:'Bruna Alves',phone:'(11) 94444-1177',email:'bruna@email.com',service:'Peeling Facial',serviceId:'peeling-facial',professional:'Laura Martins',professionalId:'laura-martins',date:dateISO(addDays(t,1)),time:'09:30',duration:45,price:150,status:'Pendente',notes:''},
{code:'AUR-55381',client:'Renata Lima',phone:'(11) 93333-8012',email:'renata@email.com',service:'Massagem Modeladora',serviceId:'massagem-modeladora',professional:'Camila Fernandes',professionalId:'camila-fernandes',date:dateISO(addDays(t,-1)),time:'14:30',duration:60,price:140,status:'Concluído',notes:''},
{code:'AUR-99102',client:'Patrícia Nunes',phone:'(11) 92222-7744',email:'patricia@email.com',service:'Limpeza de Pele',serviceId:'limpeza-de-pele',professional:'Marina Costa',professionalId:'marina-costa',date:dateISO(addDays(t,-2)),time:'11:00',duration:60,price:120,status:'Cancelado',notes:''}
]}
function seed(force=false){if(force||!localStorage.getItem(STORAGE_KEY))localStorage.setItem(STORAGE_KEY,JSON.stringify(demoData()))}seed();
let appointments=[];function load(){appointments=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(appointments))}function fmtDate(iso){return new Intl.DateTimeFormat('pt-BR').format(new Date(iso+'T12:00:00'))}
const login=document.getElementById('loginScreen'),app=document.getElementById('adminApp');function enter(){login.hidden=true;app.hidden=false;load();renderAll()}if(sessionStorage.getItem(SESSION_KEY)==='1')enter();document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('adminEmail').value.trim(),pass=document.getElementById('adminPassword').value;if(email==='admin@aurea.com'&&pass==='admin123'){sessionStorage.setItem(SESSION_KEY,'1');enter()}else document.getElementById('loginError').textContent='Credenciais demonstrativas incorretas.'});document.getElementById('logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION_KEY);location.reload()};
const nav=document.getElementById('adminNav');const titles={overview:'Visão geral',agenda:'Agenda',appointments:'Agendamentos',clients:'Clientes',treatments:'Tratamentos',settings:'Configurações'};function switchView(view){document.querySelectorAll('.admin-view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('viewTitle').textContent=titles[view];document.getElementById('sidebar').classList.remove('open');if(view==='agenda')renderAgenda();if(view==='appointments')renderAppointments();if(view==='clients')renderClients()}nav.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view)});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));document.getElementById('sidebarToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
function renderMetrics(){const today=todayISO(),weekEnd=dateISO(addDays(new Date(),7));const data=[['Agendamentos hoje',appointments.filter(a=>a.date===today&&a.status!=='Cancelado').length,'agenda ativa'],['Esta semana',appointments.filter(a=>a.date>=today&&a.date<=weekEnd&&a.status!=='Cancelado').length,'próximos 7 dias'],['Concluídos',appointments.filter(a=>a.status==='Concluído').length,'histórico'],['Cancelamentos',appointments.filter(a=>a.status==='Cancelado').length,'histórico']];document.getElementById('metrics').innerHTML=data.map(([l,n,s])=>`<div class="metric"><span>${l}</span><strong>${n}</strong><small>${s}</small></div>`).join('')}
function renderNext(){const now=new Date(),today=todayISO(),hh=now.toTimeString().slice(0,5);const next=appointments.filter(a=>a.status!=='Cancelado'&&a.status!=='Concluído'&&(a.date>today||(a.date===today&&a.time>=hh))).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0]||appointments.find(a=>a.status!=='Cancelado');document.getElementById('nextAppointment').innerHTML=next?`<div class="next-appointment"><div class="next-time">${next.time}</div><div class="next-copy"><strong>${next.client}</strong><span>${next.service}<br>${next.professional}</span></div><span class="status ${next.status.toLowerCase()}">${next.status}</span></div>`:'<p>Nenhum atendimento próximo.</p>'}
function renderChart(){const labels=['Seg','Ter','Qua','Qui','Sex','Sáb'];const vals=[5,7,4,8,6,9];document.getElementById('barChart').innerHTML=vals.map((v,i)=>`<div class="bar-col"><div class="bar" style="height:${v*16}px"></div><span>${labels[i]}</span></div>`).join('')}
function agendaFor(date){return appointments.filter(a=>a.date===date).sort((a,b)=>a.time.localeCompare(b.time))}function renderTodayAgenda(){const data=agendaFor(todayISO());document.getElementById('todayAgenda').innerHTML=data.length?data.map(a=>agendaItem(a)).join(''):`<div class="agenda-item free"><span class="agenda-time">09:00</span><div><strong>Disponível</strong><small>Horário livre</small></div></div>`}function agendaItem(a){return `<div class="agenda-item"><span class="agenda-time">${a.time}</span><div><strong>${a.client}</strong><small>${a.service} • ${a.professional}</small></div><span class="status ${a.status.toLowerCase()}">${a.status}</span></div>`}
function renderAgenda(){const input=document.getElementById('agendaDate');if(!input.value)input.value=todayISO();const data=agendaFor(input.value);const slots=['09:00','10:30','12:00','13:30','15:00','16:00','17:30'];document.getElementById('agendaList').innerHTML=slots.map(t=>{if(t==='12:00')return `<div class="agenda-item free"><span class="agenda-time">12:00</span><div><strong>Intervalo</strong><small>Horário reservado para pausa</small></div></div>`;const a=data.find(x=>x.time===t);return a?agendaItem(a):`<div class="agenda-item free"><span class="agenda-time">${t}</span><div><strong>Disponível</strong><small>Horário livre</small></div></div>`}).join('')}document.getElementById('agendaDate').addEventListener('change',renderAgenda);
function renderAppointments(){const q=document.getElementById('searchFilter').value.toLowerCase(),status=document.getElementById('statusFilter').value;const rows=appointments.filter(a=>(!q||a.client.toLowerCase().includes(q)||a.code.toLowerCase().includes(q))&&(!status||a.status===status)).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));document.getElementById('appointmentsTable').innerHTML=rows.map(a=>`<tr><td><strong>${a.code}</strong></td><td>${a.client}<br><small>${a.phone}</small></td><td>${a.service}</td><td>${a.professional}</td><td>${fmtDate(a.date)}</td><td>${a.time}</td><td><span class="status ${a.status.toLowerCase()}">${a.status}</span></td><td><div class="action-menu"><button data-action="confirm" data-code="${a.code}">Confirmar</button><button data-action="complete" data-code="${a.code}">Concluir</button><button data-action="cancel" data-code="${a.code}">Cancelar</button><button class="danger" data-action="delete" data-code="${a.code}">Excluir</button></div></td></tr>`).join('')||'<tr><td colspan="8">Nenhum agendamento encontrado.</td></tr>'}
document.getElementById('searchFilter').addEventListener('input',renderAppointments);document.getElementById('statusFilter').addEventListener('change',renderAppointments);
function renderClients(){const map={};appointments.filter(a=>a.status!=='Cancelado').forEach(a=>{if(!map[a.phone])map[a.phone]={name:a.client,phone:a.phone,count:0};map[a.phone].count++});document.getElementById('clientGrid').innerHTML=Object.values(map).map(c=>`<div class="client-card"><strong>${c.name}</strong><span>${c.phone}</span><small>${c.count} atendimento${c.count>1?'s':''}</small></div>`).join('')}
function renderTreatments(){document.getElementById('treatmentsTable').innerHTML=treatments.map(t=>`<tr><td><strong>${t[0]}</strong></td><td>${t[1]}</td><td>${t[2]}</td><td>${t[3]}</td><td><span class="status confirmado">Ativo</span></td></tr>`).join('')}
function renderAll(){document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date());renderMetrics();renderNext();renderChart();renderTodayAgenda();renderAgenda();renderAppointments();renderClients();renderTreatments()}
const confirmModal=document.getElementById('confirmModal'),confirmText=document.getElementById('confirmText');let pendingAction=null;function ask(text,fn){confirmText.textContent=text;pendingAction=fn;confirmModal.classList.add('show');confirmModal.setAttribute('aria-hidden','false')}document.getElementById('cancelConfirm').onclick=()=>confirmModal.classList.remove('show');document.getElementById('acceptConfirm').onclick=()=>{pendingAction?.();confirmModal.classList.remove('show')};function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
document.getElementById('appointmentsTable').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=appointments.find(x=>x.code===b.dataset.code);if(!a)return;const map={confirm:'Confirmado',complete:'Concluído',cancel:'Cancelado'};if(map[b.dataset.action]){a.status=map[b.dataset.action];save();renderAll();toast(`Agendamento marcado como ${a.status.toLowerCase()}.`)}else if(b.dataset.action==='delete'){ask(`Deseja realmente excluir ${a.code} de ${a.client}?`,()=>{appointments=appointments.filter(x=>x.code!==a.code);save();renderAll();toast('Agendamento excluído.')})}});
document.getElementById('resetDemo').onclick=()=>ask('Isso apagará os agendamentos criados durante a apresentação e restaurará os dados fictícios iniciais.',()=>{seed(true);load();renderAll();toast('Demonstração restaurada.')});document.querySelector('.save-demo').onclick=()=>toast('Configurações demonstrativas salvas visualmente.');
